### ISSUE TITLE
Carpentry workshop organized by Dev on Feb 22-23

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/Coordination#1]
We had been tentatively scheduling a Feb workshop and had agreed to help Dev organize a workshop from the plant pathology group. Those items now overlap. We need to decide how to proceed.

I got this email from Dev last week:

Hi Matthew,

Our club would like to move ahead with organizing the Data Carpentry Workshop on Feb 22-23, 2018.

We want to focus on the “Data analysis and visualization in R” lesson.

I think the currently on-going carpentry workshop lesson plan (https://ufrmeetup.github.io/2018-01-18-UF-R/) would be a perfect fit for us as well.

The idea would be to spread these lessons into a regular 2-day workshop type.

The workshop will be open to all. We are planning to charge $20 per person for a maximum of 30 people in order to offset money for lunch and coffee. Our club’s account is under UF Agronomy Department for financial purposes.

I have reserved Room 451 at the Cancer & Genetics Research Complex for the workshop.

In this regards, we would need help with:

Instructors
Feedback on the schedule of lessons
Eventbrite setup and fund transfer to club account
Other relevant items that we are not aware of.
 
Please let me know what you think of this and we can talk in detail as we move forward.

Looking forward to your suggestions.

My reply:

Yes, great. I was hoping you would like to keep that date. The Carpentry elections are over so we have a real board now. Let's put this on our first meeting agenda, probably next week.

Some things to think about that we've learned/done since we last talked:

- The instructor training is now March 5 & 6, we had talked about doing this workshop after the instructor training but now it will be before
- The UFII is already reserved by us for the 22 & 23rd if you want to use that classroom but cancer & genetics probably fits your audience better
- The last workshop (this Monday and Tues) did not fill up so we think we have hit saturation for advertisements on the UFII mailing list, we need to advertise elsewhere but it sounds like you have a target group to get participants from

I'll email you soon with a meeting poll. Please let me know if there are others who would like to attend.

**Comment by Cactusolo** [comment]
It looks a perfect plan! 

However, I have two comments about that:
* _It would be perfect arrangement if this workshop comes after the instructor training, which will provide a good opportunity for new instructors to perform what they newly trained.  If the date Feb. 22-23 is fixed, the potential instructors can still practices, which would make their check-out teaching demo easier._


*_My concern is as Matt noticed, our workshop (Jan 22-23) did not fill up, and it could be also true for this workshop in Feb. Because the "UFL R-Gators Spring 2018 Data Carpentry" workshop organized by Justin and Shawn is not over yet, and it would be R session "dplyr Joins" on Feb 22 (https://docs.google.com/spreadsheets/d/1MiY1md9rcwXVi1n4Az3OOJT9T4A8KsyUiba_jZirKoU/edit#gid=0). I really hope we could avoid such overlap. We don't want to do the same type workshop at the same day at two neighborhood places (if change to UFII) by two group people whom basically from the same organization. (Pardon me if I exaggerate)_

**Comment by dpaudel** [comment]
We could do our workshop at a later date too, after the instructor training is over. Feb 22-23 was based on previous meetings. This idea might be better to avoid the overlap as well. If we could come up with a tentative week for our training then I will ask club members to see which date would be the best for everyone.

**Comment by ha0ye** [comment]
re: the overlap

To me, the primary concern there is that instructor time is limited, so "spending" it on a workshop that covers similar material on the same day potentially excludes people who can't make that day, or are in more need of other materials.

I am less concerned that it is because R has been covered too many times at UF. Saturation is a possibility, but I would bet it has more to do with us generating enough interest in the workshops. It would be worthwhile to discuss at upcoming board meetings how to generate roadmaps for attendees, and promoting workshops that people want to take and that they would benefit the most from (not necessarily the same thing.)

**Comment by mjcollin** [comment]
Closing due to lack of action.
