### ISSUE TITLE
Membership Renewal Planning

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#103]
Target: $15,000

Existing commitments:
* $3,750 from UFII/UFBI
* $7,500 from IFAS (out of $10,000 -- diverting $2,500 for REC workshop program)
* $1,500 from Health Science Center Libraries / UF Libraries

Updated incentives plan:
* early registration:
    - open half the seats early (registration system can accommodate this)
    - send e-mail to all sponsoring groups with the link
    - at appropriate time (1 week later?) open regular registration
* ~~instructor training slots?~~ 
* ~~input into workshop schedule and topics?~~ 
* include long-term schedule of workshops

TODO:
- [ ] @gklarenberg will prepare statistics on workshop participants to include with $$$ request e-mails
- [x] formalized description of incentive plan, to be voted on at next board meeting

Orgs:
- [ ] ~~UFII~~
- [ ] ~~UFBI~~
- [x] WEC (@ha0ye and @picardis )
- [x] Museum (@stuckyb and @gaurav )
- [x] Biology (@elisemorrison )
- [ ] EPI
- [ ] Social Sciences?
- [ ] ~~UF Libraries / Health Science Libraries~~

**Comment by gklarenberg** [comment]
I will keep following up with Dean Davis. Spoke to him at the Biodiversity Symposium and subsequently got him in touch with Alethea (to get their financial people to talk to her). Pam was there too and indicated she'd be funding the same amount as last year.

**Comment by picardis** [comment]
Re: action item from last week's meeting (I was supposed to upload the email template from last year's funding solicitation) - turns out it's already there! SwC_DC_UF/Budget/2018_Renewal_Email. However, that one is geared to potential new sponsors. I added a new file (Funding_solicitation_template_current_sponsors) with a draft email to request support renewal from Depts that are already sponsoring us. Please edit/comment!
