### ISSUE TITLE
List Board positions and duties

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#15]

**Comment by justinmillar** [comment]
For the remainder of the Spring semester the board positions are:
Chair: Justin Millar
Secretary: Simona Picardi
Treasurer: Matt Collins

**Comment by picardis** [comment]
I am listing here duties of the board members according to my understanding - please correct me if I am wrong or add if I forgot something!

President/Chair - Organize and coordinate meetings, propose agenda
Secretary - Take notes at meetings and post them online (meeting minutes)
Treasurer - Keep track of Club's financial status, coordinate grants and funding

**Comment by mjcollin** [comment]
I thought about this and I'd like to phrase it as what is the driving question of each position instead of listing specific actions. I think this phrasing would make it possible for people to bring more ideas to the positions:

- Chair: Is the board making the needed decisions?
- Treasurer: How much can we spend?
- Secretary: Are the decisions and activities recorded publicly?
- Communications: Have the club activities been communicated to our audiences?
- Membership: Will there be a club next year?
- Workshop Coordinator: Are the workshops as good as possible?

With more roles and more specificity I think we should also move towards letting people pick what they're best at/want to be best at instead of pure random assignment.

+1s or concerns before I write up a new section to the charter?

**Comment by ha0ye** [comment]
Are you thinking of the last 3 as specific roles or as self-organized committees? I'm wondering about letting some actions slip by if the roles are exclusive and that particular member misses a meeting.

**Comment by mjcollin** [comment]
I'm all for more egalitarian task assignment but I think the roles defined by the questions I listed (or some version of them, I won't claim to have gotten the quantity and phrasing of them perfect 1st try) need to be present to have a successful group.

**Comment by stuckyb** [comment]
We've continued this discussion at the last two board meetings, and now seems like a good time to add an update here.  Here are key decisions made so far:

* The chairperson and secretary positions will rotate every two meetings.  This is intended to give everyone an opportunity to do these things and also to share the burden among all board members.  However, board members taking on long-term positions (see next point) can opt out of these two roles if they prefer.
* We see a need for two more positions, treasurer and communications coordinator, that would be full-term appointments.  For these positions, we felt that the benefits of continuity with having single appointments outweighed the benefits of having multiple members fill the roles during a board term.
* We need detailed documentation for all board positions on the Club's wiki.  Note that draft documentation has already been written for the secretary and chairperson positions.  @mjcollin , would you be willing to put some documentation together for the treasurer position?

**Comment by mjcollin** [comment]
Started documentation on treasurer: https://github.com/UF-Carpentry/Coordination/wiki/Tracking-the-Budget

**Comment by ha0ye** [comment]
(We now have pages in the Coordination wiki for chair, secretary, and treasurer)
