### ISSUE TITLE
Carpentries Membership Support from the White Lab

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#27]
@ethanwhite, The board is trying to figure out budgeting for next year's Carpentries membership and we'd like to know what your  preferred level of commitment for the future. We'd also appreciate any thoughts you may have on funding streams and sustainability going forward.

**Comment by ethanwhite** [comment]
For next year I'm happy to maintain my recent contributions, which have typically been 1/4 of the membership ($3750). I think last year I ended up spending less than that, but I'm happy up to that number w/o further discussion for 2018-2019. If more is needed let me know and I'll see what I can do.

Regarding sustainability going forward their are a number of avenues. I like your discussion of departmental memberships in #24. Department budgets tend to be pretty stable so if you can get a department on board it will often relatively easy to maintain (at least until a cut of some sort comes through and the dept has to find ways to absorb it). You could think about it as being $1000/$1500 increments with one instructor training seat and some number of workshop seats associated with each $1000/$1500.

For me, I can only guarantee support for this next year. Further support is contingent on new grant funding and on me budgeting this support into Broader Impacts. Clear benefits for grant partners so that they can be included in BI will be important for this going forward. I think you could potentially treat that the same way as departments and then each year there are *n* slots available total that can be taken by either depts or grants.

Finally I think it would be really smart for UFII and UFBI to maintain meaningful stakes here (or just to commit long-term to $7500/yr each), but I don't know how tenable that is for them.
