### ISSUE TITLE
Post ResBaz Feedback

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/Coordination#45]
Make sure we collect feedback about what worked and didn't, for planning future things that we can do and which serve the audience.

**Comment by KristinaRiemer** [comment]
@ha0ye are you thinking a short survey or something?

**Comment by Cactusolo** [comment]
We also can issue feedback card for every attendee, to catch some new
angles that didn't cover in the survey if there was.

Miao

On Aug 1, 2018 at 07:36, <Kristina Riemer <notifications@github.com>>
wrote:

@ha0ye <https://github.com/ha0ye> are you thinking a short survey or
something?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/UF-Carpentry/Coordination/issues/45#issuecomment-409545406>,
or mute the thread

**Comment by ha0ye** [comment]
Board has compiled notes and discussed this at a recent [meeting](https://www.uf-carpentry.org/minutes/board-2018-08-28/).
