### ISSUE TITLE
Agenda items for Board Meeting on March 26, 2019

### ISSUE THREAD

**Issue by josephaandreoli** [UF-Carpentry/Coordination#92]
Hi all,
Here's the agenda I have so far for our board meeting next week. Please suggest additional items in the comments. 

- Approve last week's [minutes](https://www.uf-carpentries.org/minutes/board-2019-03-12/)
- EPI workshop updates
- Update on IFAS meeting 3/15/19
- Status on logo design for April/May
- Status on travel awards
- Google and Twitter accounts
- 3rd Annual Symposium: Collaborations in Biodiversity Research Workshop 
Monday May 6, 2019
- ResBaz preliminary planning and coordination tabled. Open github issue if not already opened
- Long-term workshop schedule

**Comment by stuckyb** [comment]
Pam Soltis asked me about the possibility of running a 1- or 2-day workshop in coordination with this year's UFBI symposium, which is on May 6.  She said that UFBI could cover all workshop costs so that there are no charges for participants.  I told her we'd discuss this at our next board meeting and then get back to her.  I also invited her to attend, but she will be out of town.

**Comment by picardis** [comment]
* Update on TREC workshop organization (discuss waitlist and/or priority spots)
